defmodule QuizApp.Repo.Migrations.AddQuizTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quiz_attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :submitted_at, :utc_datetime_usec
      add :score, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:questions, primary_key: false) do
      add :question_id, :text, null: false, primary_key: true
      add :question_text, :text, null: false
      add :options, {:array, :text}, null: false
      add :correct_option_index, :bigint, null: false
      add :expert_rationale, :text, null: false
      add :display_order, :bigint, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:questions, [:display_order],
             name: "questions_unique_display_order_index"
           )

    create unique_index(:questions, [:question_id], name: "questions_unique_question_id_index")

    create table(:answers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :selected_option_index, :bigint, null: false
      add :user_justification, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :quiz_attempt_id,
          references(:quiz_attempts,
            column: :id,
            name: "answers_quiz_attempt_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :question_id,
          references(:questions,
            column: :question_id,
            name: "answers_question_id_fkey",
            type: :text,
            prefix: "public"
          ), null: false
    end

    create unique_index(:answers, [:quiz_attempt_id, :question_id],
             name: "answers_unique_answer_per_question_index"
           )
  end

  def down do
    drop_if_exists unique_index(:answers, [:quiz_attempt_id, :question_id],
                     name: "answers_unique_answer_per_question_index"
                   )

    drop constraint(:answers, "answers_quiz_attempt_id_fkey")

    drop constraint(:answers, "answers_question_id_fkey")

    drop table(:answers)

    drop_if_exists unique_index(:questions, [:question_id],
                     name: "questions_unique_question_id_index"
                   )

    drop_if_exists unique_index(:questions, [:display_order],
                     name: "questions_unique_display_order_index"
                   )

    drop table(:questions)

    drop table(:quiz_attempts)
  end
end
